version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    command: npm run dev
    volumes:
      - .:/code
      - /code/node_modules/
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
